const numero1 = 10
const numero2 = 20
const numero3 = 30
const numero4 = 40                       
const numero5 = 50
const numero6 = 60
const numero7 = 70
const numero8 = 2





console.log ("resultado de "+ numero3 +"-"+ numero4+"="+ (numero3 - numero4)) // SUBTRAÇÃO ok FUP(01)

console.log ("resultado de "+ numero1 +"+"+ numero2+"="+ (numero1 + numero2)) // SOMA

console.log ("resultado de "+ numero5 +"*"+ numero6+"="+ (numero5 * numero6)) // MULTIPLICAÇÃO ok FUP(02)

console.log ("resultado de "+ numero7 +"/"+ numero8+"="+ (numero7 / numero8)) // DIVISÃO ok FUP(03)



// CONSTANTE = TESTES ACIMA!
//FUP(04) = DROBRO DE UM NUMERO
let num1 = 10
const num2 = 2
const resultado = num1 * num2
console.log ("Dobro do Num1")
console.log ("Resultado " + num1 + " * " + num2 + " = " + resultado)

//FUP(05) = Calcule a media de 3 numeros
let n1 = 15
let n2 = 25
let n3 = 35
const media = (n1 + n2 + n3) / 3
console.log ("Media dos 3 numeros")
console.log ("Resultado " + "(" + n1 + " + " + n2 + " + " + n3 + ") / 3 = " + media)

// FUP(06) = Converta a temperatura de Celsius para Fahrenheit
let celsius = 35
const fahrenheit = (celsius * 9/5) + 32
console.log ("Conversão de Celsius para Fahrenheit")
console.log (celsius + "°C é igual a " + fahrenheit + "°F")


 


